name: Frontend approve Workflow                                   # name: 워크플로우 이름(Actions 목록/실행 화면에 표기)

on:
  push:                                                           # push: 지정 브랜치/경로 변경 시 트리거
    branches: [ "main" ]                                          # ← 트리거 대상 브랜치
    paths:                                                        # 신청 페이지 관련 파일 변경에만 반응 (불필요 실행 방지)
      - 'frontend/approve/*'                                      # ← 이 경로 하위 "한 단계" 파일만 감지(*) / (선택) 하위 폴더까지 포함하려면 '**' 사용 가능: frontend/approve/**
  workflow_dispatch:                                              # workflow_dispatch: 수동 실행 허용(액션 탭에서 Run workflow 버튼)

# env: 이 워크플로우 전체 스코프의 셸 환경변수(편의상 매핑)
#  - ${{ vars.* }} 는 Environment → Repository → Organization 우선순위로 값을 가져옴
#  - 이 파일은 잡에서 environment: approve 를 사용하므로, approve 환경의 변수 우선
env:
  AWS_REGION: ${{ vars.AWS_REGION }}                              # Repository > Settings > Secrests and variables > Action > Variables > Repository variables
  AWS_OIDC_ROLE_ARN: ${{ vars.AWS_OIDC_ROLE_ARN }}
  ECR_REPOSITORY: ${{ vars.ECR_REPO_APPROVE }}

permissions:
  id-token: write                                                 # OIDC 토큰 발급(AssumeRoleWithWebIdentity에 필요)
  contents: read                                                  # 코드 체크아웃 등 읽기 권한

jobs:
  build-and-ecr-push:                                             # jobs.<id>: 잡 식별자
    name: DockerImageECRPush                                      # name: 잡 표시 이름
    runs-on: ubuntu-latest                                        # runs-on: 실행 러너(ubuntu-latest 권장)
    environment: approve                                          # environment: 이 잡이 사용할 GitHub Environment 이름 - 이 환경에 등록한 Variables/Secrets를 ${{ vars.* }}, ${{ secrets.* }} 로 참조

# 코드 체크아웃
    steps:
    - name: Checkout
      uses: actions/checkout@v4
# AWS 자격증명 구성: GitHub OIDC로 IAM Role
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}                          # 위 env에서 매핑한 리전 사용 (Repository variables 사용)
        role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}               # 위 env에서 매핑한 Role ARN 사용 (Repository variables 사용)
        role-session-name: gha-ecr-fe-approve                      # 세션 이름(CloudTrail 등에서 식별용)
# Amazon ECR 로그인(도커 레지스트리 로그인)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
# Docker 이미지 빌드 & ECR 푸시
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}    # ECR 레지스트리 도메인(로그인 스텝 출력값) AWS ECR URI
        # 이미지 태그: Environment 변수 APPROVE_VERSION 사용 
        #  - (주의) 동일 태그 재푸시 시 기존 이미지가 덮어쓰기 됨
        #  - (선택) ECR 태그 불변(immutability)을 켠 경우 동일 태그 재푸시는 실패
        #  - (선택) 커밋 SHA를 쓰고 싶다면 ${{ github.sha }} 로 교체 가능 -> 워크플로우 트리거 한 git commit 해시 값
        IMAGE_TAG: ${{ vars.APPROVE_VERSION }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        # docker build:
        
        #  - 빌드 컨텍스트: ${{ vars.DOCKER_CONTEXT_REQUEST }} (예: ./frontend/request)
        #  - Dockerfile 경로는 기본값(Dockerfile)로 가정
        #    (선택) 별도 경로/파일명일 경우 -f 옵션 사용 필요(여기서는 원본 유지)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ vars.DOCKER_CONTEXT_APPROVE }}

        # docker push: 위에서 빌드한 태그를 ECR로 푸시
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        # 출력 변수 기록(다른 스텝에서 outputs로 활용 가능)
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
